# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: flotilla.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66lotilla.proto\x12\x08\x66lotilla\"\x1b\n\x0b\x65\x63hoMessage\x12\x0c\n\x04text\x18\x01 \x01(\t2E\n\x0b\x45\x64geService\x12\x36\n\x04\x45\x63ho\x12\x15.flotilla.echoMessage\x1a\x15.flotilla.echoMessage\"\x00\x42\x10\n\x0c\x61pp.flotillaP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flotilla_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\014app.flotillaP\001'
  _ECHOMESSAGE._serialized_start=28
  _ECHOMESSAGE._serialized_end=55
  _EDGESERVICE._serialized_start=57
  _EDGESERVICE._serialized_end=126
# @@protoc_insertion_point(module_scope)
